
endpoints:
  - name: "{{.assertoor_endpoint_name}}"
    executionUrl: "{{.execution_client_url}}"
    consensusUrl: "{{.consensus_client_url}}"

web:
  server:
    host: "0.0.0.0"
    port: "{{.http_port_number}}"
  frontend:
    enabled: true
    debug: true
    pprof: true