
endpoints:
  - name: "{{.assertoor_endpoint_name}}"
    executionUrl: "{{.execution_client_url}}"
    consensusUrl: "{{.consensus_client_url}}"

web:
  server:
    host: "0.0.0.0"
    port: "{{.http_port_number}}"
  frontend:
    enabled: true
    debug: true
    pprof: true

tests:
# First Test
- name: "Client Health Checks"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    timeout: 5m
    config:
      minClientCount: 1

  - name: sleep
    title: "Sleep 5 sec"
    config:
      duration: 5s
  - name: run_command
    title: "Run test command"
    config:
      command:
        - echo
        - "hi"

  cleanupTasks:
  - name: run_command
    title: "Cleanup command"
    config:
      command:
      - sh
      - -c
      - echo 'cleanup'
      allowed_to_fail: true

# Second Test
- name: "Every client pair proposed block"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    timeout: 5m
    config:
      minClientCount: 1

  - name: sleep
    title: "Sleep 5 sec just for fun"
    config:
      duration: 5s

  - name: run_command
    title: "Run test command"
    config:
      command:
        - echo
        - "hi"

externalTests:
- file: "https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/validator-lifecycle-test-v2.yaml"
  name: "Validator Lifecycle Test"
  timeout: 672h
  config:
    walletPrivkey: "12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625" # Kurtosis CDK admin key

- file: "https://raw.githubusercontent.com/jhkimqd/assertoor/refs/heads/jihwan/custom-l1-tests/playbooks/stable/validator-withdrawal-test.yaml"
  name: "Validator Withdrawl Test"
  timeout: 1h
  config: {}
