---
name: kurtosis-cdk-setup
description: Install tools to deploy the CDK stack with Kurtosis

inputs:
  kurtosis_version:
    description: The version of kurtosis
    required: false
    default: '0.89'

runs:
  using: "composite"
  steps:
    # Install kurtosis
    - name: Install kurtosis
      shell: bash
      run: |
        apt update
        apt install sudo
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=${{ inputs.kurtosis_version }}
        kurtosis version

    - name: Disable kurtosis analytics
      shell: bash
      run: kurtosis analytics disable

    # Install yq
    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    # Install foundry
    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1
