site_name: Polygon CDK Kurtosis package documentation

theme:
  name: material

  features:
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    #- navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

nav:
  - Overview: index.md
  - Deploy and manage a CDK stack:
    - Deploy the CDK stack: quickstart/deploy-stack.md
    - Set up a permissionless node: quickstart/set-up-permissionless-node.md
    - Observability: quickstart/observability.md
    - Breakdown the deployment: quickstart/breakdown-deployment.md
  - How to:
    - Migrate:
      - Fork id 7 to 9: how-to/migrate/forkid-7-to-9.md
      - General guide for partners: how-to/migrate/fork.md
    - Mint, bridge, and use tokens: how-to/use-native-token.md
    - Integrate a DAC: how-to/integrate-da.md
    - Manage allowlists with policies: how-to/manage-policies.md
    - Quickly test a running stack: how-to/quick-test-stack.md
    - Connect to CDK testnets: quickstart/connect-testnet.md




markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra

plugins:
  - search
  - open-in-new-tab

validation:
  absolute_links: ignore

extra_javascript:
  - https://cdnjs.cloudflare.com/polyfill/
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
