site_name: Polygon CDK Kurtosis package documentation

theme:
  name: material

  features:
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    #- navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

nav:
  - Overview: index.md
  - Getting started:
    - For technical users:
      - Deploy the CDK stack: quickstart/deploy-stack.md
      - Set up a permissionless node: quickstart/set-up-node.md
      - Observability: quickstart/observability.md
    - For developers:
      - Breakdown the deployment: quickstart/breakdown-deployment.md
      - zkEVM contracts caching: quickstart/zkevm-cache-contracts.md
  - How to:
    - Use a native token: how-to/use-native-token.md
  


markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra

plugins:
  - search
  - open-in-new-tab

validation:
  absolute_links: ignore

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
