[default]
extend-ignore-re = [
  "tar caf",
  "git checkout .*",
  "groth16", # zk proof type
]

[default.extend-identifiers]
SP1_VERIFIER_GROTH16 = "SP1_VERIFIER_GROTH16"
SP1_VERIFIER_GATEWAY_GROTH16 = "SP1_VERIFIER_GATEWAY_GROTH16"
AceptableInacctivityTime = "AceptableInacctivityTime" # typos in legacy node config
supress_rpc_check = "supress_rpc_check" # typo in blutgang config

[files]
extend-exclude = ["*go.mod", "*go.sum", "*.excalidraw"]
