ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Common]
IsValidiumMode = true
ContractVersions = "banana"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[SequenceSender]
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
MaxTxSizeForL1 = 131072
L2Coinbase =  "0x5b06837A43bdC3dD9F114558DAf4B26ed49842Ed"
PrivateKey = {Path = "/etc/cdk/sequencer.keystore", Password = "pSnv6Dh5s9ahuzGzH9RoCDrKAMddaX3m"}
SequencesTxFileName = "/data/sequencesender.json"
GasOffset = 80000
WaitPeriodPurgeTxFile = "15m"
MaxPendingTx = 1
MaxBatchesForL1 = 300
	[SequenceSender.StreamClient]
		Server = "cdk-erigon-sequencer-001:6900"
	[SequenceSender.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		ConsolidationL1ConfirmationBlocks = 5
		FinalizedStatusL1NumberOfBlocks = 10
		WaitReceiptMaxTime = "250ms"
		WaitReceiptCheckInterval = "8s"
		PrivateKeys = [
			{Path = "/etc/cdk/sequencer.keystore", Password = "pSnv6Dh5s9ahuzGzH9RoCDrKAMddaX3m"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "/data/ethtxmanager.json"
		[SequenceSender.EthTxManager.Etherman]
			URL = "http://el-1-geth-lighthouse:8545"
			L1ChainID = 271828
			HTTPHeaders = []

[Aggregator]
	Host = "0.0.0.0"
	Port = "50081"
	RetryTime = "30s"
	VerifyProofInterval = "30s"
	ProofStatePollingInterval = "5s"
	TxProfitabilityCheckerType = "acceptall"
	TxProfitabilityMinReward = "1.1"
	IntervalAfterWhichBatchConsolidateAnyway = "0s"
	ChainID = "10101"
	ForkId = 12
	CleanupLockedProofsInterval = "2m0s"
	GeneratingProofCleanupThreshold = "10m"
	GasOffset = 150000
	WitnessURL = "http://cdk-erigon-node-001:8123"
	
	SenderAddress = "0x351e560852ee001d5D19b5912a269F849f59479a"
	SequencerPrivateKey = {Path = "/etc/cdk/sequencer.keystore", Password = "pSnv6Dh5s9ahuzGzH9RoCDrKAMddaX3m"}
	SettlementBackend = "agglayer"
	AggLayerTxTimeout = "600s"
	AggLayerURL = "http://zkevm-agglayer-001:4444"
	
	[Aggregator.DB]
		Name = "aggregator_db"
		User = "aggregator_user"
		Password = "redacted"
		Host = "postgres-001"
		Port = "5432"
		EnableLog = false
		MaxConns = 200
	[Aggregator.Log]
		Environment = "development" # "production" or "development"
		Level = "debug"
		Outputs = ["stderr"]
	[Aggregator.StreamClient]
		Server = "cdk-erigon-sequencer-001:6900"
	[Aggregator.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		WaitReceiptMaxTime = "250ms"
		WaitReceiptCheckInterval = "1s"
		PrivateKeys = [
			{Path = "/etc/cdk/aggregator.keystore", Password = "pSnv6Dh5s9ahuzGzH9RoCDrKAMddaX3m"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = ""
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 0
		FinalizedStatusL1NumberOfBlocks = 0
		[Aggregator.EthTxManager.Etherman]
			URL = "http://el-1-geth-lighthouse:8545"
			L1ChainID = 271828
			HTTPHeaders = []
	[Aggregator.Synchronizer]
		[Aggregator.Synchronizer.DB]
			Name = "syncer_db"
			User = "syncer_user"
			Password = "redacted"
			Host = "postgres-001"
			Port = "5432"
			EnableLog = false
			MaxConns = 10
		[Aggregator.Synchronizer.Synchronizer]
			SyncInterval = "10s"
			SyncChunkSize = 1000
			GenesisBlockNumber = 1
			SyncUpToBlock = "latest"
			BlockFinality = "latest"
			OverrideStorageCheck = false
		[Aggregator.Synchronizer.Etherman]
			[Aggregator.Synchronizer.Etherman.Validium]
				Enabled = true

[RPC]

[NetworkConfig.L1]
L1ChainID = "271828"
PolAddr = "0xEdE9cf798E0fE25D35469493f43E88FeA4a5da0E"
ZkEVMAddr = "0x1Fe038B54aeBf558638CA51C91bC8cCa06609e91"
RollupManagerAddr = "0x2F50ef6b8e8Ee4E579B17619A92dE3E2ffbD8AD2"
GlobalExitRootManagerAddr = "0x1f7ad7caA53e35b4f0D138dC5CBF91aC108a2674"