PathRWData = "{{.zkevm_path_rw_data}}"
L1URL="{{.l1_rpc_url}}"
L2URL="http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"
AggLayerURL="{{.agglayer_grpc_url}}"

NetworkID = {{.zkevm_rollup_id}}
SequencerPrivateKeyPath = "{{or .zkevm_l2_sequencer_keystore_file "/etc/aggkit/sequencer.keystore"}}"
SequencerPrivateKeyPassword  = "{{.zkevm_l2_keystore_password}}"

polygonBridgeAddr = "{{.zkevm_bridge_address}}"

RPCURL = "http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"

# This values can be override directly from genesis.json
rollupCreationBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
rollupManagerCreationBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
genesisBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
[L1Config]
	URL = "{{.l1_rpc_url}}"
	chainId = "{{.l1_chain_id}}"
	polygonZkEVMGlobalExitRootAddress = "{{.zkevm_global_exit_root_address}}"
	polygonRollupManagerAddress = "{{.zkevm_rollup_manager_address}}"
	polTokenAddress = "{{.pol_token_address}}"
	polygonZkEVMAddress = "{{.zkevm_rollup_address}}"
	
[L2Config]
	GlobalExitRootAddr = "{{.zkevm_global_exit_root_l2_address}}"

[Log]
Environment = "development" # "production" or "development"
Level = "{{.log_level}}"
Outputs = ["stderr"]

[REST]
Port = "{{.aggkit_node_rest_api_port}}"
       
[AggSender]
CertificateSendInterval = "1m"
CheckSettledInterval = "5s"

[ClaimSponsor]
DBPath = "{{.zkevm_path_rw_data}}/claimsponsor.sqlite"
Enabled = "{{.enable_aggkit_claim_sponsor}}"
SenderAddr = "{{.zkevm_l2_claimsponsor_address}}"
BridgeAddrL2 = "{{.zkevm_bridge_l2_address}}"

[ClaimSponsor.EthTxManager]
PrivateKeys = [
    {Path = "/etc/aggkit/claimsponsor.keystore", Password = "{{.zkevm_l2_keystore_password}}"},
]
StoragePath = "{{.zkevm_path_rw_data}}/ethtxmanager-claimsponsor.sqlite"

[ClaimSponsor.EthTxManager.Etherman]
URL = "http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"
L1ChainID = "{{.zkevm_rollup_chain_id}}"
