[FullNodeRPCs]
# TODO switch this to permissionless
1 = "http://zkevm-node-rpc{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"

[RPC]
Host = "0.0.0.0"
Port = {{.zkevm_agglayer_port}}
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 5000

[Log]
Environment = "production" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[DB]
User = "{{.zkevm_db_agglayer_user}}"
Password = "{{.zkevm_db_agglayer_password}}"
Name = "{{.zkevm_db_agglayer_name}}"
Host = "{{.zkevm_db_agglayer_hostname}}{{.deployment_suffix}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = false
MaxConns = 200

[EthTxManager]
FrequencyToMonitorTxs = "1s"
WaitTxToBeMined = "2m"
ForcedGas = 0
GasPriceMarginFactor = 1
MaxGasPriceLimit = 0
PrivateKeys = [
	{Path = "/etc/zkevm/agglayer.keystore", Password = "{{.zkevm_l2_keystore_password}}"},
]
KMSKeyName = "" # Disable for local

[L1]
ChainID = {{.l1_network_id}}
NodeURL = "{{.l1_rpc_url}}"
RollupManagerContract = "###zkevm_l1_rollup_manager_addr###"

[Telemetry]
PrometheusAddr = "0.0.0.0:{{.zkevm_prometheus_port}}"