# https://github.com/0xPolygonHermez/zkevm-node/blob/v0.5.13/test/config/test.node.config.toml
IsTrustedSequencer = true

[Log]
Environment = "production" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[State]
        [State.DB]
        User = "{{.zkevm_db_state_user}}"
        Password = "{{.zkevm_db_state_password}}"
        Name = "{{.zkevm_db_state_name}}"
        Host = "trusted-{{.zkevm_db_state_hostname}}{{.deployment_idx}}"
        Port = "{{.zkevm_db_postgres_port}}"
        EnableLog = false
        MaxConns = 200
        [State.Batch]
                [State.Batch.Constraints]
                MaxTxsPerBatch = 300
                MaxBatchBytesSize = 120000
                MaxCumulativeGasUsed = 1125899906842624
                MaxKeccakHashes = 2145
                MaxPoseidonHashes = 252357
                MaxPoseidonPaddings = 135191
                MaxMemAligns = 236585
                MaxArithmetics = 236585
                MaxBinaries = 473170
                MaxSteps = 7570538
                MaxSHA256Hashes = 1596

[Pool]
FreeClaimGasLimit = 1500000
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize=100132
MaxTxDataBytesSize=100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
        [Pool.EffectiveGasPrice]
                Enabled = false
                L1GasPriceFactor = 0.25
                ByteGasCost = 16
                ZeroByteGasCost = 4
                NetProfit = 1
            BreakEvenFactor = 1.1
                FinalDeviationPct = 10
                EthTransferGasPrice = 0
                EthTransferL1GasPriceFactor = 0
                L2GasPriceSuggesterFactor = 0.5
        [Pool.DB]
        User = "{{.zkevm_db_pool_user}}"
        Password = "{{.zkevm_db_pool_password}}"
        Name = "{{.zkevm_db_pool_name}}"
        Host = "trusted-{{.zkevm_db_pool_hostname}}{{.deployment_idx}}"
        Port = "{{.zkevm_db_postgres_port}}"
        EnableLog = false
        MaxConns = 200

[Etherman]
URL = "{{.l1_rpc_url}}"
ForkIDChunkSize = 20000
MultiGasProvider = false
        [Etherscan]
                ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = {{.zkevm_rpc_http_port}}
ReadTimeout = "60s"
WriteTimeout = "60s"
BatchRequestsEnabled = true
BatchRequestsLimit = 500
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = true
        [RPC.WebSockets]
                Enabled = true
                Port = {{.zkevm_rpc_ws_port}}

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURL = "" # If it is empty or not specified, then the value is read from the smc.
L1SynchronizationMode = "sequential"
        [Synchronizer.L1ParallelSynchronization]
                MaxClients = 10
                MaxPendingNoProcessedBlocks = 25
                RequestLastBlockPeriod = "5s"
                RequestLastBlockTimeout = "5s"
                RequestLastBlockMaxRetries = 3
                StatisticsPeriod = "5m"
                TimeoutMainLoop = "5m"
                RollupInfoRetriesSpacing= "5s"
                FallbackToSequentialModeOnSynchronized = false
                [Synchronizer.L1ParallelSynchronization.PerformanceWarning]
                        AceptableInacctivityTime = "5s"
                        ApplyAfterNumRollupReceived = 10

[Sequencer]
DeletePoolTxsL1BlockConfirmations = 100
DeletePoolTxsCheckInterval = "12h"
TxLifetimeCheckInterval = "10m"
TxLifetimeMax = "3h"
LoadPoolTxsCheckInterval = "500ms"
StateConsistencyCheckInterval = "5s"
        [Sequencer.Finalizer]
                NewTxsWaitInterval = "100ms"
                ForcedBatchesTimeout = "5s"
                ForcedBatchesL1BlockConfirmations = 0
                ForcedBatchesCheckInterval = "10s"
                L1InfoTreeL1BlockConfirmations = 0
                L1InfoTreeCheckInterval = "10s"
                BatchMaxDeltaTimestamp = "20s"
                L2BlockMaxDeltaTimestamp = "4s"
                ResourceExhaustedMarginPct = 10
                HaltOnBatchNumber = 0
                SequentialBatchSanityCheck = false
                SequentialProcessL2Block = true
        [Sequencer.StreamServer]
                Port = {{.zkevm_data_streamer_port}}
                # FIXME: This might be a weird path, we should probably ensure we mount to a persistent volume
                Filename = "/tmp/datastream.bin"
                Version = 1
                ChainID = {{.l1_network_id}}
                Enabled = true

[SequenceSender]
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
L1BlockTimestampMargin = "5s"
MaxTxSizeForL1 = 131072
L2Coinbase = "{{.zkevm_l2_sequencer_address}}"
PrivateKey = {Path = "/etc/zkevm/sequencer.keystore", Password = "{{.zkevm_l2_keystore_password}}"}
SenderAddress = "{{.zkevm_l2_sequencer_address}}"
        [SequenceSender.StreamClient]
                Server = "zkevm-node-trusted-sequencer{{.deployment_idx}}:{{.zkevm_data_streamer_port}}"

[Aggregator]
Host = "0.0.0.0"
Port = {{.zkevm_aggregator_port}}
RetryTime = "5s"
VerifyProofInterval = "10s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"
UpgradeEtrogBatchNumber = 0
BatchProofL1BlockConfirmations = 2
{{if .is_cdk}}
## CDK Validium Specific Settings

# We should double check if this is necessary. I don't remember why the aggregator needs this
SequencerPrivateKey = {Path = "/etc/zkevm/sequencer.keystore", Password = "{{.zkevm_l2_keystore_password}}"}
SettlementBackend = "agglayer" # "l1"
AggLayerTxTimeout = "600s"
AggLayerURL = "http://zkevm-agglayer{{.deployment_idx}}:{{.zkevm_agglayer_port}}"
SenderAddress = "{{.zkevm_l2_agglayer_address}}"
{{else}}
SenderAddress = "{{.zkevm_l2_aggregator_address}}"
{{end}}

[EthTxManager]
ForcedGas = 0
PrivateKeys = [
        {Path = "/etc/zkevm/sequencer.keystore", Password = "{{.zkevm_l2_keystore_password}}"},
        {Path = "/etc/zkevm/aggregator.keystore", Password = "{{.zkevm_l2_keystore_password}}"}
]

[L2GasPriceSuggester]
Type = "default"
UpdatePeriod = "10s"
Factor = 0.5
DefaultGasPriceWei = 1000000000
MaxGasPriceWei = 0

[MTClient]
URI  = "zkevm-trusted-prover{{.deployment_idx}}:{{.zkevm_hash_db_port}}"

[Executor]
URI = "zkevm-trusted-prover{{.deployment_idx}}:{{.zkevm_executor_port}}"
MaxGRPCMessageSize = 100000000

[Metrics]
Host = "0.0.0.0"
Port = {{.zkevm_prometheus_port}}
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = {{.zkevm_pprof_port}}
ProfilingEnabled = true

[EventLog]
        [EventLog.DB]
        User = "{{.zkevm_db_event_user}}"
        Password = "{{.zkevm_db_event_password}}"
        Name = "{{.zkevm_db_event_name}}"
        Host = "trusted-{{.zkevm_db_event_hostname}}{{.deployment_idx}}"
        Port = "{{.zkevm_db_postgres_port}}"
        EnableLog = true
        MaxConns = 200

[HashDB]
User = "{{.zkevm_db_prover_user}}"
Password = "{{.zkevm_db_prover_password}}"
Name = "{{.zkevm_db_prover_name}}"
Host = "trusted-{{.zkevm_db_prover_hostname}}{{.deployment_idx}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = false
MaxConns = 200