#!/bin/bash
# Generate environment file.
# Necessary to build the application.
ENV_FILENAME=".env"

# Add an environment variable to the environment file.
add_env_var() {
  name="$1" # Must be capitalized!
  value="$2"
  echo "VITE_$name=$value" >> "$ENV_FILENAME"
}

# Create and populate the environment file.
true > "$ENV_FILENAME"

env_vars=(
  ETHEREUM_RPC_URL
  ETHEREUM_EXPLORER_URL
  ETHEREUM_BRIDGE_CONTRACT_ADDRESS
  ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT
  ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS
  ETHEREUM_ROLLUP_MANAGER_ADDRESS
  POLYGON_ZK_EVM_RPC_URL
  POLYGON_ZK_EVM_EXPLORER_URL
  POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS
  POLYGON_ZK_EVM_NETWORK_ID
  BRIDGE_API_URL
  RESOLVE_RELATIVE_URLS
  ENABLE_FIAT_EXCHANGE_RATES
  FIAT_EXCHANGE_RATES_API_URL
  FIAT_EXCHANGE_RATES_API_KEY
  FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS
  ENABLE_OUTDATED_NETWORK_MODAL
  OUTDATED_NETWORK_MODAL_TITLE
  OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1
  OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2
  OUTDATED_NETWORK_MODAL_URL
  ENABLE_DEPOSIT_WARNING
  ENABLE_REPORT_FORM
  REPORT_FORM_URL
  REPORT_FORM_ERROR_ENTRY
  REPORT_FORM_PLATFORM_ENTRY
  REPORT_FORM_URL_ENTRY
)
for var in "${env_vars[@]}"; do
  add_env_var "$var"
done

echo "Generated .env file:"
cat "$ENV_FILENAME"
