datadir: ./data/dynamic-kurtosis-sequencer
chain: dynamic-kurtosis


http.addr: 0.0.0.0
http.api: [eth, debug, net, trace, web3, erigon, zkevm]
http.corsdomain: "*"
http.port: {{.zkevm_rpc_http_port}}
http.vhosts: "*"
http: true

private.api.addr: localhost:9092
torrent.port: 42070
txpool.disable: false
ws: true
externalcl: true

zkevm.address-admin: "{{.zkevm_admin_address}}"
zkevm.address-ger-manager: "{{.zkevm_global_exit_root_address}}"
zkevm.address-rollup: "{{.zkevm_rollup_manager_address}}"
zkevm.address-sequencer: "{{.zkevm_l2_sequencer_address}}"
zkevm.address-zkevm: "{{.zkevm_rollup_address}}"
zkevm.data-stream-host: "0.0.0.0"
zkevm.data-stream-port: {{.zkevm_data_stream_port}}
zkevm.datastream-version: 2
zkevm.executor-strict: false

zkevm.l1-chain-id: {{.l1_chain_id}}
zkevm.l1-first-block: 1
zkevm.l1-matic-contract-address: "{{.pol_token_address}}"
zkevm.l1-rollup-id: 1
zkevm.l1-rpc-url: {{.l1_rpc_url}}
zkevm.l2-chain-id: {{.zkevm_rollup_chain_id}}

zkevm.rpc-ratelimit: 250
# zkevm.sequencer-initial-fork-id: 9
