datadir: ./data/dynamic-kurtosis-sequencer
chain: dynamic-kurtosis
http: true
private.api.addr: localhost:9092
zkevm.l2-chain-id: {{.zkevm_rollup_chain_id}}
zkevm.l1-chain-id: {{.l1_chain_id}}
zkevm.l1-rpc-url: {{.l1_rpc_url}}

zkevm.address-sequencer: "{{.zkevm_l2_sequencer_address}}"
zkevm.address-zkevm: "{{.zkevm_rollup_address}}"
zkevm.address-admin: "{{.zkevm_admin_address}}"
zkevm.address-rollup: "{{.zkevm_rollup_manager_address}}"
zkevm.address-ger-manager: "{{.zkevm_global_exit_root_address}}"

zkevm.l1-rollup-id: 1
zkevm.l1-matic-contract-address: "{{.pol_token_address}}"
zkevm.l1-first-block: 1
zkevm.executor-strict: false
zkevm.data-stream-port: {{.zkevm_data_stream_port}}
zkevm.data-stream-host: "0.0.0.0"

zkevm.rpc-ratelimit: 250
txpool.disable: false
torrent.port: 42070
zkevm.datastream-version: 2
zkevm.sequencer-initial-fork-id: 9
# zkevm.executor-urls: "zkevm-prover{{.deployment_suffix}}:{{.zkevm_executor_port}}"

externalcl: true
http.port: {{.zkevm_rpc_http_port}}
http.api: [eth, debug, net, trace, web3, erigon, zkevm]
http.addr: 0.0.0.0
http.vhosts: "*"
http.corsdomain: "*"
ws: true
