---
name: kurtosis-cdk-setup
description: Install tools to deploy the CDK stack with Kurtosis

inputs:
  kurtosis-version:
    description: The version of kurtosis
    required: false
    default: "1.0.0" # https://github.com/kurtosis-tech/kurtosis/releases
  polycli-version:
    description: The version of polygon-cli
    required: false
    default: "v0.1.52" # https://github.com/0xPolygon/polygon-cli/releases

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=${{ inputs.kurtosis-version }}
        kurtosis version

    - name: Disable kurtosis analytics
      shell: bash
      run: kurtosis analytics disable

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install polycli
      shell: bash
      run: |
        curl -L --output /tmp/polycli_${{ inputs.polycli-version }}_linux_amd64.tar.gz \
          https://github.com/0xPolygon/polygon-cli/releases/download/${{ inputs.polycli-version }}/polycli_${{ inputs.polycli-version }}_linux_amd64.tar.gz
        pushd /tmp
        tar -xvzf polycli_${{ inputs.polycli-version }}_linux_amd64.tar.gz
        sudo mv polycli_${{ inputs.polycli-version }}_linux_amd64 /usr/local/bin/polycli
        polycli version
