{
 "title": "Services",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "targets": [
      {
       "expr": "process_open_fds{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PromHTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(code) (promhttp_metric_handler_requests_total{job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests In Flight",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(promhttp_metric_handler_requests_in_flight{job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Etherman",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Events Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(etherman_get_events_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(etherman_get_events_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(etherman_get_events_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Read & Process All Events Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(etherman_read_and_process_all_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(etherman_read_and_process_all_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(etherman_read_and_process_all_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Process All Events Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(etherman_process_all_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(etherman_process_all_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(etherman_process_all_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Process Single Event Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(etherman_process_single_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(etherman_process_single_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(etherman_process_single_event_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Verify Genesis Block Number Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(etherman_verify_genesisBlockNum_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(etherman_verify_genesisBlockNum_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(etherman_verify_genesisBlockNum_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Get Fork IDs Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(etherman_get_forkIDs_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(etherman_get_forkIDs_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(etherman_get_forkIDs_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  },
  {
   "title": "AggLayer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transaction Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "get_tx_status_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Transaction Status Confirmed",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(get_tx_status_confirmed_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Transaction Status Sent",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(get_tx_status_sent_total)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Send Tx Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "max by(rollup_id) (send_tx_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Check Tx Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
     "targets": [
      {
       "expr": "max by(rollup_id) (check_tx_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Verify Signature Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "max by(rollup_id) (verify_signature_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execute Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "max by(rollup_id) (execute_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Settle Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
     "targets": [
      {
       "expr": "max by(rollup_id) (settle_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Verify ZKP Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "max by(rollup_id) (verify_zkp_total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Handled",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(job) (jsonrpc_request_handled{job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(jsonrpc_request_duration_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(jsonrpc_request_duration_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(jsonrpc_request_duration_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Provers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aggregator_current_connected_provers)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Working Provers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aggregator_current_working_provers)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Synchronizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Full L1 Sync Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_full_L1_sync_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_full_L1_sync_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_full_L1_sync_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Process L1 Data Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_process_L1_data_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_process_L1_data_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_process_L1_data_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Read L1 Data Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_read_L1_data_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_read_L1_data_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_read_L1_data_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Full Trusted Sync Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_full_trusted_sync_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_full_trusted_sync_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_full_trusted_sync_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Get Trusted Batch Number Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_get_trusted_batchNumber_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_get_trusted_batchNumber_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_get_trusted_batchNumber_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "State Executor Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(state_executor_processing_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(state_executor_processing_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(state_executor_processing_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Get Trusted Batch Info Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_get_trusted_batchInfo_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_get_trusted_batchInfo_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_get_trusted_batchInfo_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Initialization Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_initialization_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_initialization_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_initialization_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    },
    {
     "title": "Process Trusted Batch Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, job) (rate(synchronizer_process_trusted_batch_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p50 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le, job) (rate(synchronizer_process_trusted_batch_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p75 {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, job) (rate(synchronizer_process_trusted_batch_time_bucket{job=~\"$job\"}[$__rate_interval])))",
       "legendFormat": "p95 {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Checker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Checks",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      { "expr": "status_check", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Status Checks Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum by(check) (status_check{success=\"false\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Bridge Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network 0 Full L1 Sync Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expression": "$B / $A", "type": "math" }
     ]
    },
    {
     "title": "Network 0 Process L1 Data Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expression": "$B / $A", "type": "math" }
     ]
    },
    {
     "title": "Network 0 Read L1 Data Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expression": "$B / $A", "type": "math" }
     ]
    },
    {
     "title": "Network 1 Read & Process All Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expression": "$B / $A", "type": "math" }
     ]
    },
    {
     "title": "Network 1 Process All Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expression": "$B / $A", "type": "math" }
     ]
    },
    {
     "title": "Network 1 Process Single Event",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expression": "$B / $A", "type": "math" }
     ]
    },
    { "title": "Number of Reorgs", "type": "timeseries", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 }, "fieldConfig": { "defaults": { "unit": "s" } } },
    { "title": "Last Reorged Block", "type": "timeseries", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 }, "fieldConfig": { "defaults": { "unit": "s" } } }
   ]
  }
 ]
}