name: kurtosis-pre-run
description: Prepare the environment for deploying Kurtosis packages.

inputs:
  docker_username:
    description: The username for Docker Hub
    required: false
  docker_token:
    description: The token for Docker Hub
    required: false

runs:
  using: composite
  steps:
    - name: Login to docker registry
      if: ${{ inputs.docker_username && inputs.docker_token }}
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install -y kurtosis-cli=1.7.2
        kurtosis analytics disable
        kurtosis version
    
    - name: Install jq
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y jq

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1
      with:
        version: v1.0.0
    
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13
    
    - name: Add registry prefix to image names
      shell: bash
      run: python3 scripts/add-registry-prefix.py --registry-prefix "europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/virtual"
