grpc-endpoint = "0.0.0.0:{{ .aggkit_prover_grpc_port }}"

[log]
level = "{{ .log_level }}"
outputs = []
format = "json"

[telemetry]
prometheus-addr = "0.0.0.0:{{ .metrics_port }}"

[shutdown]
runtime-timeout = "5s"

[aggchain-proof-service.aggchain-proof-builder]
network-id = {{ .network_id }}

[aggchain-proof-service.aggchain-proof-builder.primary-prover.{{ .primary_prover }}]
proving-timeout = "1h"

[aggchain-proof-service.aggchain-proof-builder.proving-timeout]
secs = 3600
nanos = 0

[aggchain-proof-service.aggchain-proof-builder.contracts]
l1-rpc-endpoint = "{{.l1_rpc_url}}"
l2-execution-layer-rpc-endpoint = "{{ .l2_el_rpc_url }}"
l2-consensus-layer-rpc-endpoint = "{{ .l2_cl_rpc_url }}"
polygon-rollup-manager = "{{ .rollup_manager_address }}"
global-exit-root-manager-v2-sovereign-chain = "{{ .global_exit_root_address }}"

[aggchain-proof-service.proposer-service]
l1-rpc-endpoint = "{{ .l1_rpc_url }}"
mock = {{ .op_succinct_mock }}

[aggchain-proof-service.proposer-service.client]
proposer-endpoint = "{{ .proposer_url }}"
sp1-cluster-endpoint = "{{ .agglayer_prover_network_url }}"
request-timeout = 600
proving-timeout = 3600

[primary-prover.{{ .primary_prover }}]
proving-timeout = "1h"
