[Log]
Level = "info"
Environment = "production"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
User = "{{.bridge_db.user}}"
Name = "{{.bridge_db.name}}"
Password = "{{.bridge_db.password}}"
Host = "{{.bridge_db.hostname}}"
Port = "{{.bridge_db.port}}"
MaxConns = 20

[Etherman]
l1URL = "{{.l1_rpc_url}}"
L2URLs = ["http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"]

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "{{.zkevm_bridge_grpc_port}}"
HTTPPort = "{{.zkevm_bridge_rpc_port}}"
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    # Read only
    [BridgeServer.DB]
    Database = "postgres"
    User = "{{.bridge_db.user}}"
    Name = "{{.bridge_db.name}}"
    Password = "{{.bridge_db.password}}"
    Host = "{{.bridge_db.hostname}}"
    Port = "{{.bridge_db.port}}"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
PolygonBridgeAddress = "{{.zkevm_bridge_address}}"
PolygonZkEVMGlobalExitRootAddress = "{{.zkevm_global_exit_root_address}}"
PolygonRollupManagerAddress = "{{.zkevm_rollup_manager_address}}"
PolygonZkEVMAddress = "{{.zkevm_rollup_address}}"
L2PolygonBridgeAddresses = ["{{.zkevm_bridge_address}}"]

[ClaimTxManager]
FrequencyToMonitorTxs = "5s"
PrivateKey = {Path = "/etc/zkevm/claimtxmanager.keystore", Password = "{{.zkevm_l2_keystore_password}}"}
Enabled = true
RetryInterval = "1s"
RetryNumber = 10