---
deployment_idx: "001"

# Databases
zkevm_db_postgres_port: 5432

zkevm_db_prover_hostname: "prover-db"
zkevm_db_prover_user: "prover_user"
zkevm_db_prover_password: "SR5xq2KZPgvQkPDranCRhvkv6pnqfo77"

zkevm_db_pool_hostname: "pool-db"
zkevm_db_pool_user: "pool_user"
zkevm_db_pool_password: "Qso5wMcLAN3oF7EfaawzgWKUUKWM3Vov"

zkevm_db_event_hostname: "event-db"
zkevm_db_event_user: "event_user"
zkevm_db_event_password: "rJXJN6iUAczh4oz8HRKYbVM8yC7tPeZm"

zkevm_db_state_hostname: "state-db"
zkevm_db_state_user: "state_user"
zkevm_db_state_password: "rHTX7EpajF8zYDPatN32rH3B2pn89dmq"
