{
 "title": "Kurtosis CDK",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   { "name": "provider", "query": { "query": "label_values(provider)" } }
  ]
 },
 "panels": [
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_height{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Blocks Observed",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_block{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gas Used (million gas)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Base Fee Per Gas (gwei)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_base_fee_per_gas{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Gas Limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_gas_limit{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Block Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_difficulty{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_block_size{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uncles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(panoptichain_rpc_uncles{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions Per Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transactions Per Block",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(le) (panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Transaction Value (ETH)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Gas Tip Cap (gwei)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Gas Price (gwei)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Gas Limit (gas)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Transaction Cost (ETH)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  },
  { "title": "Batches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Last Batch Sequenced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max by(rollup) (panoptichain_rpc_zkevm_last_batch_sequenced{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "rollup: {{rollup}}"
    }
   ]
  },
  {
   "title": "Time Since Last Batch Sequenced",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_zkevm_time_since_last_sequenced{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sequenced Batches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_zkevm_total_sequenced_batches{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Verified Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by(rollup) (panoptichain_rpc_zkevm_last_verified_batch{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "rollup: {{rollup}}"
    }
   ]
  },
  {
   "title": "Time Since Last Verified Batch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_zkevm_time_since_last_verified{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Verified Batches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_zkevm_total_verified_batches{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Force Batch Sequenced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by(rollup) (panoptichain_rpc_zkevm_last_force_batch{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "rollup: {{rollup}}"
    }
   ]
  },
  {
   "title": "Reward Per Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_zkevm_reward_per_batch{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_zkevm_batch_fee{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exit Roots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Exit Root Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_global_exit_roots{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mainnet Exit Root Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_mainnet_exit_roots{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rollup Exit Root Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_rollup_exit_roots{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Since Last Global Exit Root",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_time_since_last_global_exit_root{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Since Last Mainnet Exit Root",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_time_since_last_mainnet_exit_root{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Since Last Rollup Exit Root",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_time_since_last_rollup_exit_root{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "zkEVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bridge Deposit Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_bridge_deposit_count{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bridge Last Updated Deposit Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_bridge_last_updated_deposit_count{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rollup Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_zkevm_rollup_count{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rollup Type Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(panoptichain_rpc_zkevm_rollup_type_count{network=~\"$network\", provider=~\"$provider\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregator Balances (ETH)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "avg by(address) (panoptichain_rpc_zkevm_aggregator_balance{network=~\"$network\", provider=~\"$provider\"}) / 1000000000000000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Trusted Sequencer Balances",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "avg by(token) (panoptichain_rpc_zkevm_trusted_sequencer_balance{network=~\"$network\", provider=~\"$provider\"}) / 1000000000000000000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Panoptichain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Panoptichain Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_system_uptime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refresh State Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_system_refresh_state_time_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_system_refresh_state_time_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_system_refresh_state_time_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "AggLayer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total Transaction Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(get_tx_status_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transaction Status Confirmed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(get_tx_status_confirmed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transaction Status Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(get_tx_status_sent_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Send Tx Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "max by(rollup_id) (send_tx_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Check Tx Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "max by(rollup_id) (check_tx_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verify Signature Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "max by(rollup_id) (verify_signature_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execute Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "max by(rollup_id) (execute_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Settle Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "targets": [
    {
     "expr": "max by(rollup_id) (settle_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verify ZKP Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "max by(rollup_id) (verify_zkp_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}