{
 "title": "Panoptichain",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   { "name": "provider", "query": { "query": "label_values(provider)" } }
  ]
 },
 "panels": [
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_height{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blocks Observed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_block{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Used (million gas)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_gas_used_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Base Fee Per Gas (gwei)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_base_fee_per_gas{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Gas Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_gas_limit{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_difficulty{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_block_size{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_uncles{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Transactions Per Block",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(le) (increase(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transactions Per Block",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(le) (panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transactions Per Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transactions_per_block_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Transaction Cost (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Transaction Cost (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_cost_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_pending_tx_size{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Gas Price (gwei)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_price_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Transaction Gas Limit (gas)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_limit_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Queued Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_queued_tx_size{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Gas Tip Cap (gwei)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_gas_tip_cap_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Transaction Value (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_rpc_transaction_value_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Validator Wallet Balance (ETH)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "avg by(signer_address) (panoptichain_rpc_validator_wallet_balance{network=~\"$network\", provider=~\"$provider\"}) / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Block Proposals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "avg by(signer_address) (panoptichain_heimdall_missed_block_proposal{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Checkpoint ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_heimdall_checkpoint_id{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Since Last Checkpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_heimdall_time_since_last_checkpoint{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  { "title": "State Syncs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "State Sync ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_state_sync_id{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Since Last State Sync",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(panoptichain_rpc_time_since_last_state_sync{network=~\"$network\", provider!=\"blxrbdn.com\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Sync ID Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    { "expression": "$A - $B", "type": "math" },
    { "expression": "$D - $E", "type": "math" }
   ]
  },
  { "title": "Milestones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Milestone Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "panoptichain_heimdall_milestone_count{network=~\"$network\", provider=~\"$provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Since Last Milestone",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "panoptichain_heimdall_time_since_last_milestone{network=~\"$network\", provider=~\"$provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milestone Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  { "title": "Heimdall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Heimdall Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_heimdall_height{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heimdall Total Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "panoptichain_heimdall_total_transaction_count{network=~\"$network\", provider=~\"$provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heimdall Signatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "panoptichain_heimdall_signatures{network=~\"$network\", provider=~\"$provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heimdall Block Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(panoptichain_heimdall_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(panoptichain_heimdall_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(panoptichain_heimdall_block_interval_bucket{network=~\"$network\", provider=~\"$provider\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "zkEVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Trusted Batch Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_trusted_batch{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verified Batch Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(panoptichain_rpc_verified_batch{network=~\"$network\", provider=~\"$provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Number Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  }
 ]
}