[Log]
Level = "info"
Environment = "production"
Outputs = ["stderr"]

[SyncDB]
# Type of database to use (e.g., postgres)
Database = "postgres"
    [SyncDB.PgStorage]
    # Username for database authentication
    User = "{{.bridge_db.user}}"
    # Name of the database to connect to
    Name = "{{.bridge_db.name}}"
    # Password for the database user
    Password = "{{.bridge_db.password}}"
    # Host address of the database server
    Host = "{{.bridge_db.hostname}}"
    # Port number on which the database server is listening
    Port = "{{.bridge_db.port}}"
    # Maximum number of concurrent connections to the database
    MaxConns = 20

[Etherman]
l1URL = "{{.l1_rpc_url}}"
L2URLs = ["{{.op_el_rpc_url}}"]

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
DefaultPageLimit = 25
MaxPageLimit = 1000
BridgeVersion = "v1"
# Read only
    [BridgeServer.DB]
    # Type of database for the bridge server
    Database = "postgres"
        [BridgeServer.DB.PgStorage]
        # Database user for authentication
        User = "{{.bridge_db.user}}"
        # Database name for the bridge server
        Name = "{{.bridge_db.name}}"
        # Password for the database user
        Password = "{{.bridge_db.password}}"
        # Host address of the database server
        Host = "{{.bridge_db.hostname}}"
        # Port number for the database connection
        Port = "{{.bridge_db.port}}"
        # Maximum number of connections to the database for the bridge server
        MaxConns = 20

[NetworkConfig]
GenBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
PolygonBridgeAddress = "{{.zkevm_bridge_address}}"
PolygonZkEVMGlobalExitRootAddress = "{{.zkevm_global_exit_root_address}}"
PolygonRollupManagerAddress = "{{.zkevm_rollup_manager_address}}"
PolygonZkEVMAddress = "{{.sovereign_rollup_addr}}"
L2PolygonBridgeAddresses = ["{{.sovereign_bridge_proxy_addr}}"]

RequireSovereignChainSmcs = [true]
L2PolygonZkEVMGlobalExitRootAddresses = ["{{.sovereign_ger_proxy_addr}}"]

[ClaimTxManager]
FrequencyToMonitorTxs = "5s"
PrivateKey = {Path = "/etc/zkevm/claimtx.keystore", Password = "{{.zkevm_l2_keystore_password}}"}
Enabled = true
RetryInterval = "1s"
RetryNumber = 10

[Metrics]
Enabled = true
Host = "0.0.0.0"
Port = "{{.zkevm_bridge_metrics_port}}"