[Log]
Level = "info"
Environment = "production"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
User = "{{.sovereign_bridge_db.user}}"
Name = "{{.sovereign_bridge_db.name}}"
Password = "{{.sovereign_bridge_db.password}}"
Host = "{{.sovereign_bridge_db.hostname}}"
Port = "{{.sovereign_bridge_db.port}}"
MaxConns = 20

[Etherman]
l1URL = "http://el-1-geth-lighthouse:8545"
L2URLs = ["http://op-el-1-op-geth-op-node-op-kurtosis:8545"]

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
DefaultPageLimit = 25
MaxPageLimit = 1000
BridgeVersion = "v1"
# Read only
[BridgeServer.DB]
Database = "postgres"
User = "{{.sovereign_bridge_db.user}}"
Name = "{{.sovereign_bridge_db.name}}"
Password = "{{.sovereign_bridge_db.password}}"
Host = "{{.sovereign_bridge_db.hostname}}"
Port = "{{.sovereign_bridge_db.port}}"
MaxConns = 20

[NetworkConfig]
GenBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
PolygonBridgeAddress = "{{.zkevm_bridge_address}}"
PolygonZkEVMGlobalExitRootAddress = "{{.zkevm_global_exit_root_address}}"
PolygonRollupManagerAddress = "{{.zkevm_rollup_manager_address}}"
PolygonZkEVMAddress = "{{.sovereign_rollup_addr}}"
L2PolygonBridgeAddresses = ["{{.sovereign_bridge_proxy_addr}}"]

RequireSovereignChainSmcs = [true]
L2PolygonZkEVMGlobalExitRootAddresses = ["{{.sovereign_ger_proxy_addr}}"]

[ClaimTxManager]
FrequencyToMonitorTxs = "5s"
PrivateKey = {Path = "/etc/zkevm/claimtx.keystore", Password = "{{.zkevm_l2_keystore_password}}"}
Enabled = true
RetryInterval = "1s"
RetryNumber = 10