PrivateKey = {Path = "/etc/zkevm/dac.keystore", Password = "{{.zkevm_l2_keystore_password}}"}

[L1]
WsURL = "{{.l1_ws_url}}"
RpcURL = "{{.l1_rpc_url}}"
PolygonValidiumAddress = "{{.zkevm_rollup_address}}"
DataCommitteeAddress = "{{.polygon_data_committee_address}}"
Timeout = "1m"
RetryPeriod = "5s"
BlockBatchSize = "64"
GenesisBlock = "0"
TrackSequencer = false

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[DB]
User = "{{.dac_db_user}}"
Password = "{{.dac_db_password}}"
Name = "{{.dac_db_name}}"
Host = "{{.dac_db_hostname}}"
Port = "{{.dac_db_port}}"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = {{.zkevm_dac_port}}
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500