IsTrustedSequencer = false
ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Log]
Environment = "development"
Level = "info"
Outputs = ["stderr"]

[Etherman]
URL = "http://localhost:8545"
ForkIDChunkSize = 20000
MultiGasProvider = false

[Etherman.Etherscan]
ApiKey = ""
Url = ""

[EthTxManager]
FrequencyToMonitorTxs = "1s"
WaitTxToBeMined = "2m0s"
ForcedGas = 0
GasPriceMarginFactor = 1
MaxGasPriceLimit = 0

[Pool]
IntervalToRefreshBlockedAddresses = "5m0s"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize = 100132
MaxTxDataBytesSize = 100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m0s"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
ForkID = 0

[Pool.DB]
Name = "pool_db"
User = "pool_user"
Password = "pool_password"
Host = "zkevm-pool-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool.EffectiveGasPrice]
Enabled = false
L1GasPriceFactor = 0.25
ByteGasCost = 16
ZeroByteGasCost = 4
NetProfit = 1
BreakEvenFactor = 1.1
FinalDeviationPct = 10
EthTransferGasPrice = 0
EthTransferL1GasPriceFactor = 0
L2GasPriceSuggesterFactor = 0.5

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeout = "1m0s"
WriteTimeout = "1m0s"
MaxRequestsPerIPAndSecond = 500
SequencerNodeURI = ""
MaxCumulativeGasUsed = 0
EnableL2SuggestedGasPricePolling = true
BatchRequestsEnabled = false
BatchRequestsLimit = 20
L2Coinbase = "0x0000000000000000000000000000000000000000"
MaxLogsCount = 10000
MaxLogsBlockRange = 10000
MaxNativeBlockHashBlockRange = 60000
EnableHttpLog = true

[RPC.WebSockets]
Enabled = true
Host = "0.0.0.0"
Port = 8546
ReadLimit = 104857600

[RPC.ZKCountersLimits]
MaxKeccakHashes = 0
MaxPoseidonHashes = 0
MaxPoseidonPaddings = 0
MaxMemAligns = 0
MaxArithmetics = 0
MaxBinaries = 0
MaxSteps = 0
MaxSHA256Hashes = 0

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURL = ""
SyncBlockProtection = "safe"
L1SyncCheckL2BlockHash = true
L1SyncCheckL2BlockNumberhModulus = 30
L1SynchronizationMode = "sequential"

[Synchronizer.L1ParallelSynchronization]
MaxClients = 10
MaxPendingNoProcessedBlocks = 25
RequestLastBlockPeriod = "5s"
RequestLastBlockTimeout = "5s"
RequestLastBlockMaxRetries = 3
StatisticsPeriod = "5m0s"
TimeOutMainLoop = "5m0s"
RollupInfoRetriesSpacing = "5s"
FallbackToSequentialModeOnSynchronized = false

[Synchronizer.L1ParallelSynchronization.PerformanceWarning]
AceptableInacctivityTime = "5s"
ApplyAfterNumRollupReceived = 10

[Synchronizer.L2Synchronization]
AcceptEmptyClosedBatches = false
ReprocessFullBatchOnClose = false
CheckLastL2BlockHashOnCloseBatch = true

[Sequencer]
DeletePoolTxsL1BlockConfirmations = 100
DeletePoolTxsCheckInterval = "12h0m0s"
TxLifetimeCheckInterval = "10m0s"
TxLifetimeMax = "3h0m0s"
LoadPoolTxsCheckInterval = "500ms"
StateConsistencyCheckInterval = "5s"

[Sequencer.Finalizer]
ForcedBatchesTimeout = "1m0s"
NewTxsWaitInterval = "100ms"
ResourceExhaustedMarginPct = 10
ForcedBatchesL1BlockConfirmations = 64
L1InfoTreeL1BlockConfirmations = 64
ForcedBatchesCheckInterval = "10s"
L1InfoTreeCheckInterval = "10s"
BatchMaxDeltaTimestamp = "10s"
L2BlockMaxDeltaTimestamp = "3s"
HaltOnBatchNumber = 0
SequentialBatchSanityCheck = false
SequentialProcessL2Block = true

[Sequencer.Finalizer.Metrics]
Interval = "1h0m0s"
EnableLog = true

[Sequencer.StreamServer]
Port = 0
Filename = ""
Version = 0
ChainID = 0
Enabled = false
UpgradeEtrogBatchNumber = 0

[Sequencer.StreamServer.Log]
Environment = ""
Level = ""

[SequenceSender]
WaitPeriodSendSequence = "5s"
LastBatchVirtualizationTimeMaxWaitPeriod = "5s"
L1BlockTimestampMargin = "30s"
MaxTxSizeForL1 = 131072
# SenderAddress = "0x0000000000000000000000000000000000000000"
# L2Coinbase = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
ForkUpgradeBatchNumber = 0
GasOffset = 80000
MaxBatchesForL1 = 300

[SequenceSender.PrivateKey]
Path = "/pk/sequencer.keystore"
Password = "testonly"

[Aggregator]
Host = "0.0.0.0"
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "1m30s"
ProofStatePollingInterval = "5s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = 1100000000000000000
IntervalAfterWhichBatchConsolidateAnyway = "0s"
ChainID = 0
ForkId = 0

CleanupLockedProofsInterval = "2m0s"
GeneratingProofCleanupThreshold = "10m"
GasOffset = 0
UpgradeEtrogBatchNumber = 0

AggLayerTxTimeout = "5m0s"
BatchProofL1BlockConfirmations = 2
SettlementBackend = "agglayer"
# SenderAddress = ""
# AggLayerURL = "http://zkevm-agglayer"

[Aggregator.SequencerPrivateKey]
Path = "/pk/sequencer.keystore"
Password = "testonly"

[NetworkConfig]
[NetworkConfig.l1Config]
chainId = 0
polygonZkEVMAddress = "0x0000000000000000000000000000000000000000"
polygonRollupManagerAddress = "0x0000000000000000000000000000000000000000"
polTokenAddress = "0x0000000000000000000000000000000000000000"
polygonZkEVMGlobalExitRootAddress = "0x0000000000000000000000000000000000000000"

[NetworkConfig.Genesis]
RollupBlockNumber = 0
RollupManagerBlockNumber = 0
Root = "0x0000000000000000000000000000000000000000000000000000000000000000"

[L2GasPriceSuggester]
Type = "follower"
DefaultGasPriceWei = 2000000000
MaxGasPriceWei = 0
CheckBlocks = 0
Percentile = 0
UpdatePeriod = "10s"
CleanHistoryPeriod = "1h0m0s"
CleanHistoryTimeRetention = "5m0s"
Factor = 0.15

[Executor]
URI = "zkevm-prover:50071"
MaxResourceExhaustedAttempts = 3
WaitOnResourceExhaustion = "1s"
MaxGRPCMessageSize = 100000000

[MTClient]
URI = "zkevm-prover:50061"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
ProfilingHost = ""
ProfilingPort = 0
ProfilingEnabled = false

[EventLog.DB]
Name = ""
User = ""
Password = ""
Host = ""
Port = ""
EnableLog = false
MaxConns = 0

[HashDB]
Name = "prover_db"
User = "prover_user"
Password = "prover_pass"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[State]
MaxCumulativeGasUsed = 0
ChainID = 0
MaxResourceExhaustedAttempts = 0
WaitOnResourceExhaustion = "0s"
ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0
MaxLogsCount = 0
MaxLogsBlockRange = 0
MaxNativeBlockHashBlockRange = 0
AvoidForkIDInMemory = false

[State.DB]
Name = "state_db"
User = "state_user"
Password = "state_password"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[State.Batch.Constraints]
MaxTxsPerBatch = 300
MaxBatchBytesSize = 120000
MaxCumulativeGasUsed = 1125899906842624
MaxKeccakHashes = 2145
MaxPoseidonHashes = 252357
MaxPoseidonPaddings = 135191
MaxMemAligns = 236585
MaxArithmetics = 236585
MaxBinaries = 473170
MaxSteps = 7570538
MaxSHA256Hashes = 1596
