# https://github.com/0xPolygonHermez/zkevm-node/blob/v0.5.13/test/config/test.node.config.toml
IsTrustedSequencer = true
ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Log]
Environment = "production" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[Etherman]
URL = "{{.l1_rpc_url}}"
ForkIDChunkSize = 20000
MultiGasProvider = false

[Etherman.Etherscan]
ApiKey = ""
Url = ""

[EthTxManager]
FrequencyToMonitorTxs = "1s"
WaitTxToBeMined = "2m0s"
ForcedGas = 0
GasPriceMarginFactor = 1
MaxGasPriceLimit = 0

[[EthTxManager.PrivateKeys]]
Path = "/etc/zkevm/sequencer.keystore"
Password = "{{.zkevm_l2_keystore_password}}"

[[EthTxManager.PrivateKeys]]
Path = "/etc/zkevm/aggregator.keystore"
Password = "{{.zkevm_l2_keystore_password}}"


[Pool]
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize=100132
MaxTxDataBytesSize=100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
ForkID = 0

[Pool.DB]
User = "{{.zkevm_db_pool_user}}"
Password = "{{.zkevm_db_pool_password}}"
Name = "{{.zkevm_db_pool_name}}"
Host = "{{.zkevm_db_pool_hostname}}{{.deployment_suffix}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = false
MaxConns = 200

[Pool.EffectiveGasPrice]
Enabled = false
L1GasPriceFactor = 0.25
ByteGasCost = 16
ZeroByteGasCost = 4
NetProfit = 1
BreakEvenFactor = 1.1
FinalDeviationPct = 10
EthTransferGasPrice = 0
EthTransferL1GasPriceFactor = 0
L2GasPriceSuggesterFactor = 0.5

[RPC]
Host = "0.0.0.0"
Port = {{.zkevm_rpc_http_port}}
ReadTimeout = "1m0s"
WriteTimeout = "1m0s"
MaxRequestsPerIPAndSecond = 500
SequencerNodeURI = ""
MaxCumulativeGasUsed = 0
EnableL2SuggestedGasPricePolling = true
BatchRequestsEnabled = false
BatchRequestsLimit = 20
L2Coinbase = "0x0000000000000000000000000000000000000000"
MaxLogsCount = 10000
MaxLogsBlockRange = 10000
MaxNativeBlockHashBlockRange = 60000
EnableHttpLog = true

[RPC.WebSockets]
Enabled = true
Host = "0.0.0.0"
Port = {{.zkevm_rpc_ws_port}}
ReadLimit = 104857600

[RPC.ZKCountersLimits]
MaxKeccakHashes = 0
MaxPoseidonHashes = 0
MaxPoseidonPaddings = 0
MaxMemAligns = 0
MaxArithmetics = 0
MaxBinaries = 0
MaxSteps = 0
MaxSHA256Hashes = 0

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURL = ""
SyncBlockProtection = "safe"
L1SyncCheckL2BlockHash = true
L1SyncCheckL2BlockNumberhModulus = 30
L1SynchronizationMode = "sequential"

[Synchronizer.L1ParallelSynchronization]
MaxClients = 10
MaxPendingNoProcessedBlocks = 25
RequestLastBlockPeriod = "5s"
RequestLastBlockTimeout = "5s"
RequestLastBlockMaxRetries = 3
StatisticsPeriod = "5m0s"
TimeOutMainLoop = "5m0s"
RollupInfoRetriesSpacing = "5s"
FallbackToSequentialModeOnSynchronized = false

[Synchronizer.L1ParallelSynchronization.PerformanceWarning]
AceptableInacctivityTime = "5s"
ApplyAfterNumRollupReceived = 10

[Synchronizer.L2Synchronization]
AcceptEmptyClosedBatches = false
ReprocessFullBatchOnClose = false
CheckLastL2BlockHashOnCloseBatch = true

[Sequencer]
DeletePoolTxsL1BlockConfirmations = 100
DeletePoolTxsCheckInterval = "12h0m0s"
TxLifetimeCheckInterval = "10m0s"
TxLifetimeMax = "3h0m0s"
LoadPoolTxsCheckInterval = "500ms"
StateConsistencyCheckInterval = "5s"

[Sequencer.Finalizer]
ForcedBatchesTimeout = "1m0s"
NewTxsWaitInterval = "100ms"
ResourceExhaustedMarginPct = 10
ForcedBatchesL1BlockConfirmations = 64
L1InfoTreeL1BlockConfirmations = 64
ForcedBatchesCheckInterval = "10s"
L1InfoTreeCheckInterval = "10s"
BatchMaxDeltaTimestamp = "5s"
L2BlockMaxDeltaTimestamp = "3s"
HaltOnBatchNumber = 0
SequentialBatchSanityCheck = false
SequentialProcessL2Block = true

[Sequencer.Finalizer.Metrics]
Interval = "1h0m0s"
EnableLog = true

[Sequencer.StreamServer]
Port = {{.zkevm_data_streamer_port}}
# FIXME: This might be a weird path, we should probably ensure we mount to a persistent volume
Filename = "/tmp/datastream.bin"
Version = 0
ChainID = {{.l1_chain_id}}
Enabled = true
UpgradeEtrogBatchNumber = 0

[Sequencer.StreamServer.Log]
Environment = "production"
Level = "debug"


[SequenceSender]
WaitPeriodSendSequence = "5s"
LastBatchVirtualizationTimeMaxWaitPeriod = "5s"
L1BlockTimestampMargin = "30s"
MaxTxSizeForL1 = 131072
ForkUpgradeBatchNumber = 0
GasOffset = 80000
MaxBatchesForL1 = 300
L2Coinbase = "{{.zkevm_l2_sequencer_address}}"
SenderAddress = "{{.zkevm_l2_sequencer_address}}"

[SequenceSender.PrivateKey]
Path = "/etc/zkevm/sequencer.keystore"
Password = "{{.zkevm_l2_keystore_password}}"

[Aggregator]
Host = "0.0.0.0"
Port = {{.zkevm_aggregator_port}}
RetryTime = "5s"
VerifyProofInterval = "5m0s"
ProofStatePollingInterval = "5s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1100000000000000000"
IntervalAfterWhichBatchConsolidateAnyway = "0s"
ChainID = 0
ForkId = 0
CleanupLockedProofsInterval = "2m0s"
GeneratingProofCleanupThreshold = "10m"
GasOffset = 0
UpgradeEtrogBatchNumber = 0
{{if .is_cdk_validium}}
## CDK Validium Specific Settings
SenderAddress = "{{.zkevm_l2_agglayer_address}}"
SettlementBackend = "agglayer"
AggLayerTxTimeout = "600s"
AggLayerURL = "http://zkevm-agglayer{{.deployment_suffix}}:{{.zkevm_agglayer_port}}"
{{else}}
SenderAddress = "{{.zkevm_l2_aggregator_address}}"
{{end}}

[Aggregator.SequencerPrivateKey]
Path = "/etc/zkevm/sequencer.keystore"
Password = "{{.zkevm_l2_keystore_password}}"
# Path = "/etc/zkevm/proofsigner.keystore"
# Password = "{{.zkevm_l2_keystore_password}}"

[L2GasPriceSuggester]
Type = "follower"
DefaultGasPriceWei = 2000000000
MaxGasPriceWei = 0
CheckBlocks = 0
Percentile = 0
UpdatePeriod = "10s"
CleanHistoryPeriod = "1h0m0s"
CleanHistoryTimeRetention = "5m0s"
Factor = 0.15

[Executor]
URI = "zkevm-prover{{.deployment_suffix}}:{{.zkevm_executor_port}}"
MaxResourceExhaustedAttempts = 3
WaitOnResourceExhaustion = "1s"
MaxGRPCMessageSize = 100000000

[MTClient]
URI  = "zkevm-prover{{.deployment_suffix}}:{{.zkevm_hash_db_port}}"

[Metrics]
Host = "0.0.0.0"
Port = {{.zkevm_prometheus_port}}
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = {{.zkevm_pprof_port}}
ProfilingEnabled = true

[EventLog.DB]
User = "{{.zkevm_db_event_user}}"
Password = "{{.zkevm_db_event_password}}"
Name = "{{.zkevm_db_event_name}}"
Host = "{{.zkevm_db_event_hostname}}{{.deployment_suffix}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = true
MaxConns = 200

[HashDB]
User = "{{.zkevm_db_prover_user}}"
Password = "{{.zkevm_db_prover_password}}"
Name = "{{.zkevm_db_prover_name}}"
Host = "{{.zkevm_db_prover_hostname}}{{.deployment_suffix}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = false
MaxConns = 200

[State]
MaxCumulativeGasUsed = 0
ChainID = 0
MaxResourceExhaustedAttempts = 0
WaitOnResourceExhaustion = "0s"
ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0
MaxLogsCount = 0
MaxLogsBlockRange = 0
MaxNativeBlockHashBlockRange = 0
AvoidForkIDInMemory = false

[State.DB]
User = "{{.zkevm_db_state_user}}"
Password = "{{.zkevm_db_state_password}}"
Name = "{{.zkevm_db_state_name}}"
Host = "{{.zkevm_db_state_hostname}}{{.deployment_suffix}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = false
MaxConns = 200

[State.Batch.Constraints]
MaxTxsPerBatch = 300
MaxBatchBytesSize = 120000
MaxCumulativeGasUsed = 1125899906842624
MaxKeccakHashes = 2145
MaxPoseidonHashes = 252357
MaxPoseidonPaddings = 135191
MaxMemAligns = 236585
MaxArithmetics = 236585
MaxBinaries = 473170
MaxSteps = 7570538
MaxSHA256Hashes = 1596


