# Workflow for automatically building and pushing the config image to the Antithesis registry.
name: Antithesis

on:
  pull_request:
  workflow_dispatch:

env:
  ANTITHESIS_REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: molten-verve-216720/polygon-repository

concurrency:
  group: antithesis-build-and-push-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ${{ env.ANTITHESIS_REGISTRY }}
        username: _json_key
        password: ${{ secrets.ANTITHESIS_JSON_LOGIN_KEY }}

    - name: Build and push config image
      uses: docker/build-push-action@v6
      with:
        context: docker
        file: docker/antithesis.Dockerfile
        push: true
        tags: |
          ${{ env.ANTITHESIS_REGISTRY }}/${{ env.REPOSITORY}}/config:antithesis-latest,
          ${{ env.ANTITHESIS_REGISTRY }}/${{ env.REPOSITORY}}/config:${{ github.sha }}
