---
name: Deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ENCLAVE_NAME: cdk-v1

jobs:
  # Basic deployment workflow.
  # Note that more advanced use cases are tested in the nightly workflow.
  deploy-cdk:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis CDK tools
        uses: ./.github/actions/setup-kurtosis-cdk

      - name: Deploy Kurtosis CDK package
        run: |
          kurtosis run \
            --enclave="${{ env.ENCLAVE_NAME }}" \
            --show-enclave-inspect=false \
            --args-file=params.yml \
            . \
            '{
              "apply_workload": true,
              "args": {
                "l1_seconds_per_slot": 1
              }
            }'

      - name: Inspect enclave
        run: kurtosis enclave inspect "${{ env.ENCLAVE_NAME }}"

      - name: Monitor verified batches
        run: |
          rpc_url="$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-node-001 http-rpc)"
          ./.github/scripts/monitor-verified-batches.sh --rpc-url "$rpc_url"

  deploy-zkevm:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis CDK tools
        uses: ./.github/actions/setup-kurtosis-cdk

      - name: Deploy Kurtosis CDK package
        run: |
          kurtosis run \
            --enclave="${{ env.ENCLAVE_NAME }}" \
            --show-enclave-inspect=false \
            --args-file=params.yml \
            . \
            '{
              "deploy_zkevm_permissionless_node": true,
              "deploy_cdk_erigon_node": false,
              "apply_workload": true,
              "args": {
                "sequencer_type": "zkevm"
              }
            }'

      - name: Inspect enclave
        run: kurtosis enclave inspect "${{ env.ENCLAVE_NAME }}"

      - name: Monitor verified batches
        run: |
          rpc_url="$(kurtosis port print ${{ env.ENCLAVE_NAME }} zkevm-node-rpc-001 http-rpc)"
          ./.github/scripts/monitor-verified-batches.sh --rpc-url "$rpc_url"
