---
name: deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install kurtosis (ubuntu)
        if: runner.os == 'ubuntu'
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable

      - name: Install kurtosis (macos)
        if: runner.os == 'macos'
        run: |
          # docker is not available on macos runners: https://github.com/actions/runner-images/issues/17
          brew install docker
          colima start
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

          brew install kurtosis-tech/tap/kurtosis-cli
          kurtosis analytics disable

      - name: Deploy devnet
        run: kurtosis run --enclave cdk --args-file cdk-params.yml .
