---
name: Deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Basic deployment workflow.
  # Note that more advanced use cases are tested in the nightly workflow.
  deploy-cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis CDK tools
        uses: ./.github/actions/setup-kurtosis-cdk

      - name: Deploy Kurtosis CDK package
        run: |
          kurtosis run --enclave cdk-v1 --args-file params.yml --image-download always . '{deploy_zkevm_permissionless_node: true, apply_workload: true}'

      - name: Monitor verified batches
        uses: ./.github/actions/monitor-cdk-verified-batches
        with:
          rpc_service: cdk-erigon-node-001

      - name: Monitor verified batches (CDK Erigon RPC)
        uses: ./.github/actions/monitor-cdk-verified-batches
        with:
          rpc_service: cdk-erigon-node-001

      - name: Monitor verified batches (zkEVM Node Permissionless RPC)
        uses: ./.github/actions/monitor-cdk-verified-batches
        with:
          rpc_service: zkevm-node-rpc-pless-001

  deploy-zkevm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis CDK tools
        uses: ./.github/actions/setup-kurtosis-cdk

      - name: Deploy Kurtosis CDK package
        run: |
          kurtosis run --enclave cdk-v1 --args-file params.yml --image-download always . '{deploy_zkevm_permissionless_node: true, args: {sequencer_type: "zkevm"}, deploy_cdk_erigon_node: false, apply_workload: true}'

      - name: Monitor verified batches (zkEVM Node RPC)
        uses: ./.github/actions/monitor-cdk-verified-batches
        with:
          rpc_service: zkevm-node-rpc-001

      - name: Monitor verified batches (zkEVM Node Permissionless RPC)
        uses: ./.github/actions/monitor-cdk-verified-batches
        with:
          rpc_service: zkevm-node-rpc-pless-001
