---
name: deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cdk_package:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Deploy kurtosis package
        uses: kurtosis-tech/kurtosis-github-action@v1
        with:
          path: cdk
          args: cdk/params.yml
