---
name: deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Deploy the CDK environment in one step.
  monolithic_cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy kurtosis package
        uses: kurtosis-tech/kurtosis-github-action@v1
        with:
          path: .
          args: params.yml

  # Deploy the CDK environment incrementally, stage by stage.
  incremental_cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install tools.
      - name: Install kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable

      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install --yes yq

      # Deploy components.
      - name: Deploy L1
        run: |
          yq e '.stages = [1]' --inplace params.yml
          kurtosis run --enclave cdk-v1 --args-file params.yml .

      - name: Configure L1
        run: |
          yq e '.stages = [2]' --inplace params.yml
          kurtosis run --enclave cdk-v1 --args-file params.yml .

      - name: Deploy CDK Trusted Environment
        run: |
          yq e '.stages = [3]' --inplace params.yml
          kurtosis run --enclave cdk-v1 --args-file params.yml .

      - name: Deploy CDK Bridge
        run: |
          yq e '.stages = [4]' --inplace params.yml
          kurtosis run --enclave cdk-v1 --args-file params.yml .

      - name: Deploy Permissionless Node
        run: |
          yq e '.stages = [5]' --inplace params.yml
          kurtosis run --enclave cdk-v1 --args-file params.yml .
