---
name: Deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Basic deployment workflow.
  # Note that more advanced use cases are tested in the nightly workflow.
  deploy-cdk:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis CDK tools
        uses: ./.github/actions/setup-kurtosis-cdk

      - name: Deploy Kurtosis CDK package
        run: |
          kurtosis run --enclave cdk-v1 --args-file params.yml . \
            '{"apply_workload": true}'

      - name: Monitor verified batches
        run: |
          ./.github/scripts/monitor-verified-batches.sh\
            --rpc-url $(kurtosis port print cdk-v1 cdk-erigon-node-001 http-rpc)

  deploy-zkevm:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install Kurtosis CDK tools
        uses: ./.github/actions/setup-kurtosis-cdk

      - name: Deploy Kurtosis CDK package
        run: |
          kurtosis run --enclave cdk-v1 --args-file params.yml . \
            '{
              "deploy_zkevm_permissionless_node": true,
              "deploy_cdk_erigon_node": false,
              "apply_workload": true,
              "args": {
                "sequencer_type": "zkevm"
              }
            }'

      - name: Monitor verified batches
        run: |
          ./.github/scripts/monitor-verified-batches.sh\
            --rpc-url $(kurtosis port print cdk-v1 zkevm-node-rpc-001 http-rpc)
