---
name: deploy

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        package: ["cdk", "permissionless-node"]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy kurtosis package
        uses: kurtosis-tech/kurtosis-github-action@v1
        with:
          path: ${{ matrix.package }}
          args: ${{ matrix.package }}/params.yml
