name: docker-image-builder-cron

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 am Paris time (UTC+2).
  workflow_dispatch:

env:
  ZKEVM_BRIDGE_UI_BRANCH: develop


jobs:
  zkevm-bridge-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone zkevm-bridge-ui repository
        working-directory: /opt/zkevm-bridge-ui
        run: git clone --branch ${{ env.ZKEVM_BRIDGE_UI_BRANCH }} https://github.com/0xPolygonHermez/zkevm-bridge-ui .

      - name: Apply patches
        working-directory: /opt/zkevm-bridge-ui
        run: |
          patch -p1 -i ${{ github.workspace }}/deploy.sh.diff
          patch -p1 -i ${{ github.workspace }}/env.ts.diff

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # TODO: Use credentials to push to Polygon Devtools' GCR.
      # - name: Login to GCR
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.GCR_DEVTOOLS_USERNAME }}
      #     password: ${{ secrets.GCR_DEVTOOLS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: polygondevtools/zkevm-bridge-ui:0.0.1
          platforms: linux/amd64,linux/arm64
          push: false # TODO: Set this value to true once credentials are set.
