---
name: Docker Image Builder Cron

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM Paris time (UTC+2).
  workflow_dispatch:
  pull_request: # TODO: Remove this. This is just for testing purposes.

concurrency:
  group: docker-image-builder-cron-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ZKEVM_BRIDGE_UI_BRANCH: develop
  POLYCLI_VERSION: main

jobs:
  zkevm-contracts:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fork:
          - id: 4
            branch: v1.1.0-fork.4
          - id: 5
            branch: v2.0.0-fork.5
          - id: 6
            branch: v3.0.0-fork.6
          - id: 7
            branch: v4.0.0-fork.7
          - id: 8
            branch: v5.0.1-rc.2-fork.8
          - id: 9
            branch: develop

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/zkevm-contracts.Dockerfile
          build-args: |
            ZKEVM_CONTRACTS_BRANCH=${{ matrix.fork.branch }}
            POLYCLI_VERSION=${{ env.POLYCLI_VERSION }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zkevm-contracts:fork${{ matrix.fork.id }}
          platforms: linux/amd64,linux/arm64
          push: true

  zkevm-bridge-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone zkevm-bridge-ui repository
        run: |
          mkdir /opt/zkevm-bridge-ui
          git clone --branch ${{ env.ZKEVM_BRIDGE_UI_BRANCH }} https://github.com/0xPolygonHermez/zkevm-bridge-ui /opt/zkevm-bridge-ui

      - name: Apply patches
        working-directory: /opt/zkevm-bridge-ui
        run: |
          patch -p1 -i ${{ github.workspace }}/docker/zkevm-bridge-ui/deploy.sh.diff
          patch -p1 -i ${{ github.workspace }}/docker/zkevm-bridge-ui/env.ts.diff

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: /opt/zkevm-bridge-ui
          file: /opt/zkevm-bridge-ui/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zkevm-bridge-ui:multi-network
          platforms: linux/amd64,linux/arm64
          push: true

  workload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/workload.Dockerfile
          build-args: |
            POLYCLI_VERSION=${{ env.POLYCLI_VERSION }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/workload:0.0.1
          platforms: linux/amd64,linux/arm64
          push: true
