name: lint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Pre kurtosis run
        uses: ./.github/actions/kurtosis-pre-run
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}

      # Install linters
      - name: Install yamllint
        run: pip install yamllint

      - name: Install hadolint
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint

      - name: Install shellcheck
        run: sudo apt install shellcheck

      # Run linters
      - name: Run kurtosis linter
        run: kurtosis lint .

      - name: Run yamllint
        run: yamllint --config-file ${{ github.workspace }}/.yamllint.yml .

      - name: Run hadolint
        run: find . -type f -name '*.Dockerfile' | sort | xargs -I {} hadolint --config ${{ github.workspace }}/.hadolint.yml {}

      - name: Run shellcheck
        run: find . -type f -name '*.sh' | grep -v "./docs" | grep -v "/upgrade_forkid.sh" | sort | xargs -I {} shellcheck -x {}

  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@392b78fe18a52790c53f42456e46124f77346842 # v1.34.0

  check-test-combinations-and-cdk-version-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          pip3 install yq
          yq --version

      - name: Generate test combinations and cdk version matrix
        working-directory: .github/tests
        run: ./combine-ymls.sh

      - name: Check if test combinations and cdk version matrix are up to date
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "❌ Error: Test combinations and/or CDK version matrix are not up to date. Please run \`./combine-ymls.sh\`."
            git status --porcelain
            git diff
            exit 1
          else
            echo "✅ Test combinations are up to date."
          fi
