---
# Workflow for automatically building and deploying docker images for kurtosis-cdk.
name: OP-Succinct Docker Image Builder

on:
  workflow_dispatch:
    inputs:
      agglayer-op-succinct-commit:
        description: The agglayer/op-succinct commit to build the image from
        required: true

env:
  IMAGE_NAME: leovct/op-succinct-contract-deployer
  RUST_VERSION: 1.84.1

jobs:
  agglayer-op-succinct:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Load environment variables
        run: grep -vE '^\s*#|^\s*$' .github/workflows/.env >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ secrets.IMAGE_BUILDER_DOCKERHUB_USERNAME }}
          password: ${{ secrets.IMAGE_BUILDER_DOCKERHUB_TOKEN }}

      - name: Determine tag
        id: determine_tag
        run: |
          # Append the fork id to the image tag.
          TAG=${{ github.event.inputs.agglayer-op-succinct-commit }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Check if image already exists
        id: check_image
        run: |
          if docker manifest inspect ${{ env.IMAGE_NAME }}:${{ steps.determine_tag.outputs.tag }} > /dev/null 2>&1; then
            echo "Image already exists, skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build image and push to the Docker Hub
        if: ${{ steps.check_image.outputs.exists == 'false' }}
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: docker
          file: docker/op-succinct.Dockerfile
          build-args: |
            RUST_VERSION=${{ env.RUST_VERSION }}
            FOUNDRY_VERSION=${{ env.FOUNDRY_VERSION }}
            OP_SUCCINCT_BRANCH=${{ github.event.inputs.agglayer-op-succinct-commit }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.determine_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
