name: Test

on:
  workflow_dispatch:
  pull_request: # TODO: remove after test

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Regression Tests
        uses: 0xPolygon/kurtosis-cdk@main
