name: Test

on:
  workflow_dispatch:

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Regression Tests
        uses: 0xPolygon/kurtosis-cdk@main
